<?php

	require_once("../../gdgram.php");
	
	// New GDGram Instance
	$doc 		= new gdgram();
	
	// We load the image
	$jellyfish 	= $doc->loadImage("../RESS/Jellyfish.jpg");
	
	// We're going to scale and crop the picture to fit in a 400x200px rectangle, because it's too big
	$jellyfish		= $doc->cropfit($jellyfish, 400,200);
	
	
	// TEXT WATERMARK
	
	// We apply the text, with a 10px margin from the bottom right corner, white, size 1 (GD size).
	$jellyfish	= $doc->writeText($jellyfish, array(
		"text"		=> "Generated by GDGram",
		"right"		=> 10,
		"bottom"	=> 10,
		"color"		=> "#ffffff",
		"size"		=> 1,	// GD font size. 1 to 5. http://us2.php.net/manual/en/function.imagestring.php
		"alpha"		=> 50
	));
	
	// We apply another text, using a TTF font this time, with a 10px margin from the bottom right corner, white.
	$jellyfish	= $doc->writeText($jellyfish, array(
		"text"		=> "Generated by GDGram with a ttf font",
		"left"		=> 10,
		"bottom"	=> 10,
		"color"		=> "#ffffff",
		"font"		=> "../RESS/MotionPicture.ttf",
		"size"		=> 12,	// in pixels, since we are using a TTF font
		"alpha"		=> 50
	));
	
	// We now apply another text, centered horizontaly, 10px from the top
	$jellyfish	= $doc->writeText($jellyfish, array(
		"text"		=> "Centered ttf text",
		"center"	=> "x",	// x, xy, or y
		"top"		=> 10,
		"color"		=> "#ffffff",
		"font"		=> "../RESS/MotionPicture.ttf",
		"size"		=> 12,	// in pixels, since we are using a TTF font
		"alpha"		=> 50
	));
	
	
	// IMAGE WATERMARK
	
	
	// We load a 32x32 PNG icon, that we are going to apply as a watermark
	$icon 	= $doc->loadImage("../RESS/World-32.png");
	
	// Now we will align the logo on the jellyfish image, with an alpha=50 (alpha: 0 to 127)
	$jellyfish	= $doc->align($jellyfish, $icon, array(
		"top"		=> 10,
		"right"		=> 10,
		"alpha"		=> 50
	));
	
	// We export the generated image
	$doc->export($jellyfish, "watermark.png");
	
?>

<!DOCTYPE HTML>
<html lang="en-US">
<head>
	<title>GDGRAM</title>
	<meta charset="UTF-8">
</head>
<body style="background-color:	#ffffff">
	<img src="watermark.png?rnd=<?php echo rand(); ?>" style="border: 1px solid #000; padding: 0px;" />
</body>
</html>
